name: feedback_report_generator_project
services:
  app:
    build: .
    image: feedback_report_generator
    container_name: feedback_report_generator
    command: /app/entrypoint.sh
    ports:
    - "8000:8000"
    volumes:
    - .:/app
    depends_on:
    - postgres
    - redis
  
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    image: feedback_report_generator
    container_name: celery
    command: celery -A feedback_report worker -E -l info
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - app
  flower:
    image: feedback_report_generator
    container_name: flower
    command: celery -A feedback_report flower --basic_auth=admin:password
    ports:
      - "5555:5555"
    depends_on:
      - redis
volumes:
  postgres_data:
  redis_data:
