version: '3.9'

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER_URL=redis://127.0.0.1:6379/0
    depends_on:
      - pgdb
      - redis
  celery:
    build: .
    container_name: celery
    command: celery -A feedback_report worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - django
      - redis
  pgdb:
    image: postgres:17
    container_name: pgdb
    environment:
      POSTGRES_USER: aryan
      POSTGRES_PASSWORD: Aryan123
      POSTGRES_DB: report_db
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: redis
  
  flower:
    build: ./
    container_name: flower
    command: celery -A feedback_report flower --port=5555 --basic_auth=admin:flower123
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - pgdb
volumes:
  pgdata: