# Generated by Django 5.2 on 2025-05-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlreport',
            name='task_id',
            field=models.CharField(max_length=255),
        ),
    ]
