# Generated by Django 5.2 on 2025-05-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_htmlreport_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfreport',
            name='task_id',
            field=models.CharField(max_length=255),
        ),
    ]
